# Generated by Django 3.1 on 2021-07-08 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement_company_detail',
            name='apply_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
