# Generated by Django 3.1 on 2021-07-08 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placement_company_detail_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement_company_detail',
            name='snippet',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
