# Generated by Django 3.1 on 2021-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_placement_company_detail_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_company_detail',
            name='snippet',
            field=models.TextField(max_length=255),
        ),
    ]
