# Generated by Django 3.2.5 on 2021-07-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20210729_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResorcesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('docs', models.URLField(blank=True, null=True)),
                ('course1_title', models.CharField(max_length=255)),
                ('course1_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('course1_link', models.URLField(blank=True, null=True)),
                ('course2_title', models.CharField(max_length=255)),
                ('course2_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('course2_link', models.URLField(blank=True, null=True)),
                ('course3_title', models.CharField(max_length=255)),
                ('course3_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('course3_link', models.URLField(blank=True, null=True)),
                ('course4_title', models.CharField(max_length=255)),
                ('course4_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('course4_link', models.URLField(blank=True, null=True)),
                ('course5_title', models.CharField(max_length=255)),
                ('course5_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('course5_link', models.URLField(blank=True, null=True)),
                ('channel1_title', models.CharField(max_length=255)),
                ('channel1_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('channel1_link', models.URLField(blank=True, null=True)),
                ('channel2_title', models.CharField(max_length=255)),
                ('channel2_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('channel2_link', models.URLField(blank=True, null=True)),
                ('channel3_title', models.CharField(max_length=255)),
                ('channel3_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('channel3_link', models.URLField(blank=True, null=True)),
                ('channel4_title', models.CharField(max_length=255)),
                ('channel4_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('channel4_link', models.URLField(blank=True, null=True)),
                ('channel5_title', models.CharField(max_length=255)),
                ('channel5_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('channel5_link', models.URLField(blank=True, null=True)),
                ('Website1_title', models.CharField(max_length=255)),
                ('Website1_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('Website1_link', models.URLField(blank=True, null=True)),
                ('Website2_title', models.CharField(max_length=255)),
                ('Website2_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('Website2_link', models.URLField(blank=True, null=True)),
                ('Website3_title', models.CharField(max_length=255)),
                ('Website3_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('Website3_link', models.URLField(blank=True, null=True)),
                ('Website4_title', models.CharField(max_length=255)),
                ('Website4_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('Website4_link', models.URLField(blank=True, null=True)),
                ('Website5_title', models.CharField(max_length=255)),
                ('Website5_Img', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('Website5_link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
